# Generated by Django 4.2.7 on 2023-11-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_device', '0003_alter_device_description_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='serial',
            field=models.CharField(max_length=10),
        ),
    ]
